# Generated by Django 5.1.4 on 2024-12-20 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=10, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("address", models.CharField(max_length=100, verbose_name="адрес")),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="contact",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hr.contact"
            ),
        ),
    ]
