# Generated by Django 5.1.4 on 2024-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_contact_employee_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="email"),
        ),
    ]
