# Generated by Django 5.1.4 on 2025-02-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0004_department_employee_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compensation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="compensation",
            field=models.ManyToManyField(to="hr.compensation"),
        ),
    ]
