# Generated by Django 5.1.4 on 2025-02-13 10:29

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_compensation_employee_compensation"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[
                ("persons", django.db.models.manager.Manager()),
            ],
        ),
    ]
