# Generated by Django 5.1.4 on 2025-02-13 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0006_alter_employee_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="compensation",
        ),
        migrations.AlterModelManagers(
            name="employee",
            managers=[],
        ),
        migrations.DeleteModel(
            name="Compensation",
        ),
    ]
