# Generated by Django 5.1.4 on 2025-02-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_remove_employee_compensation_alter_employee_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="about",
            field=models.CharField(
                max_length=500, null=True, verbose_name="About employee"
            ),
        ),
    ]
